# Generated by Django 4.2.1 on 2023-06-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0002_mahsulot_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahsulot',
            name='kafolat',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mahsulot',
            name='min_miqdor',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
