# Generated by Django 4.2.1 on 2023-06-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0003_alter_mahsulot_kafolat_alter_mahsulot_min_miqdor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='rasm',
            field=models.FileField(upload_to='mahsulot'),
        ),
    ]
