# Generated by Django 4.2.1 on 2023-06-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0008_izoh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='izoh',
            name='baho',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
